### ISSUE TITLE
Setting periodic data should start sending data to all connected clients

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/ws-anywhere#5]
AFAIU this is not the case currently

**Comment by gomorizsolt** [comment]
We ended up sending the periodic messages only by clicking on the `Start` button. 

The `Submit` button behaves as a JSON validator and also posts the data depending on whether the given format is valid or not - but it doesn't start sending the data towards the connected clients automatically.

Shouldn't the issue be closed because of the reasons/changes above?

**Comment by bencevoros** [comment]
Based on these, it seems to me that you can close it

**Comment by gomorizsolt** [comment]
The issue was originally created by @thisismydesign, so let's wait for his response first. :)

**Comment by thisismydesign** [comment]
Yes, this issue is obsolete.
